spring:
  application:
    name: ticketsyncs
dynamodb:
  access: ${AWS_ACCESS_KEY}
  secret: ${AWS_SECRET_KEY}
server:
  shutdown: graceful
logging:
  level:
    root: INFO
    com.ticketsyncs.clockfarm: ${PACKAGE_LOG_LEVEL}
    web: ${WEB_LOG_LEVEL}
  file:
    path: /
    name: ticketsyncs.log
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /system