spring:
  application:
    name: ticketsyncs
  liquibase:
    url: jdbc:postgresql://${PG_HOST}:5432/postgres
    user: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://${PG_HOST}:5432/postgres
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
server:
  shutdown: graceful
logging:
  level:
    root: INFO
    com.ticketsyncs.clockfarm: ${PACKAGE_LOG_LEVEL}
    web: ${WEB_LOG_LEVEL}
    org.springframework.r2dbc: ${R2DBC_LOG_LEVEL}
  file:
    path: /
    name: ticketsyncs.log
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /system