name: Java Maven Docker CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          export PACKAGE_LOG_LEVEL=INFO
          export R2DBC_LOG_LEVEL=INFO
          export WEB_LOG_LEVEL=INFO
          mvn clean install
      - name: Build and Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: abialiauski/ticketsyncs-clockfarm
          tags: 0.0.$GITHUB_RUN_NUMBER, latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}