name: PR CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          export PACKAGE_LOG_LEVEL=INFO
          export R2DBC_LOG_LEVEL=INFO
          export WEB_LOG_LEVEL=INFO
          mvn clean install