name: 'Terraform'
on:
  push:
    branches: [ master ]
permissions:
  contents: read
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        env:
          TF_VAR_api_key: ${{ secrets.HEROKU_API_KEY }}
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_package_log_level: INFO
          TF_VAR_web_log_level: INFO
        run: terraform plan -input=false
      - name: Terraform Apply
        env:
          TF_VAR_api_key: ${{ secrets.HEROKU_API_KEY }}
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_package_log_level: INFO
          TF_VAR_web_log_level: INFO
        run: terraform apply -auto-approve -input=false